SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles

src/components/atoms/_avatar.scss

- Defined fontsize to Avatar component
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3353)

APP-3353 Rely on fontsize to define avatar dimensions

---

src/components/atoms/_avatar.scss
stories/avatar.stories.js

- Defined default fontsize to Avatar
- Update storybooks examples
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3353)

APP-3353 Define fontsize for Avatar

---

src/uitoolkit-components/_select.scss

- Fixed focus style on Dropdown
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3948)

APP-3984 Fixed focus on Dropdown

---

src/components/atoms/_avatar.scss

- Aligned avatar
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3353)

APP-3353 Aligned avatar styles

---

src/components/atoms/_hint.scss

- Fix vertical alignment on the Hint component. 
**Before**
**After fix**
[Jira link](https://perzoinc.atlassian.net/browse/APP-3737)

APP-3737 Fix vertical alignment

---

src/components/atoms/_label.scss
stories/text.stories.js

add a style tk-label--required for labels
Jira ticket:
https://perzoinc.atlassian.net/browse/EIS-2792
Feature documentation:
https://perzoinc.atlassian.net/wiki/spaces/EIS/pages/1829802777/Using+TextField+from+UI+TK+instead+of+FormInput+from+eis-common+list+of+what+needs+to+be+done+to+be+completed

EIS-2792 - required label style

---

src/components/atoms/_input.scss

https://perzoinc.atlassian.net/browse/APP-4051

APP-4051 - fix(TextField): fix disabled styles on hover

---

docs/getting-started.md
src/components/atoms/_index.scss
src/components/atoms/_toast.scss
src/variables/_z-indexes.scss
stories/toast.stories.js

- https://perzoinc.atlassian.net/wiki/spaces/DevX/pages/1930300829/Toast - Proposal
- https://perzoinc.atlassian.net/browse/APP-4097 - Ticket
- https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Component-Library - Design for Toast component

APP-4097 - Toast component

---

src/uitoolkit-components/_select.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss

- Added styles to scrollbar multiselect
Light mode
Dark mode
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3873)

APP-3873 Added styles to scrollbar multiselect

---

src/uitoolkit-components/_select.scss

https://perzoinc.atlassian.net/browse/APP-3931
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/207

APP-3937 feat(dropdown): create nested mode

---

stories/avatar.stories.js

Add and adjust some examples of the Avatar

APP-4161 - doc(avatar): update avatar examples

---

src/components/atoms/_dialog.scss

**Jira ticket**
https://perzoinc.atlassian.net/browse/APP-3965
**Changes**
Add border on close icon when focus

APP-3965 Add border on close icon when focus

---

src/utils/_spacing.scss
src/utils/_typography.scss
src/utils/functions/index.scss
src/utils/mixins/_spacing.scss

- Add !important to spacing utilty classes
[Jira-ticker](https://perzoinc.atlassian.net/browse/APP-4150)

APP-4150 Add !important to spacing utilty classes

---

src/uitoolkit-components/_select.scss
src/variables/colors/_statics.scss

- Added styles to loading dropdown
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-3872)

APP-3872 Added styles to loading dropdown

---

.prettierrc
docs/getting-started.md
docs/sandbox.md
stories/docs.stories.js

**Jira ticket**
https://perzoinc.atlassian.net/browse/APP-3149
**Change**
Add a link to CodeSandbox in 'Getting Started' section
---
Add new Sandbox section

APP-3149 Add CodeSandbox

---

src/utils/_typography.scss
src/utils/_utils.scss
stories/stories.scss
stories/utils.stories.js

- Align Typography variants
- Improve storybook example
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4129)

APP-4129 Align Typography variants

---

src/variables/colors/_statics.scss

- Added color palette from SDS
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4176)

APP-4176 Update color palette

---

src/variables/colors/_statics.scss

APP-4176 Update colors

---

src/components/atoms/_banner.scss
src/components/atoms/_index.scss
src/utils/mixins/_banner.scss
src/utils/mixins/_index.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss
stories/banner.stories.js

**EIS-3348: Add Banner style**
- create banner scss files (component, mixins)
- create new banner variables
- add a sample banner story
Ticket: [https://perzoinc.atlassian.net/browse/EIS-3348](https://perzoinc.atlassian.net/browse/EIS-3348)
Figma: [https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=5272%3A9287](https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=5272%3A9287)
Related PR (components): [https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/251](https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/251)
--------
**EDIT**
- icons are now injected in SASS with the icon mixin (variant icons and close icon)
- update the story so it …

EIS-3348: Add Banner style

---

LICENSE

**Jira ticket**
https://perzoinc.atlassian.net/browse/APP-4202
**Change:**
- Add Apache 2.0 license
I only replaced in the template:
`Copyright [yyyy] [name of copyright owner]`
by
`Copyright 2021 Symphony Communication Services, LLC`
(as it is the copyright written on https://symphony.com/)

APP-4202 Add a License

---

src/components/atoms/_avatar.scss

- Added min width/heigh to avatar

APP-3587 Added min width/heigh to avatar

---

src/utils/_typography.scss
src/utils/functions/index.scss
stories/utils.stories.js

- Removed width:100% from typography
- Use of math division

APP-4289 Fix Typography style

---

src/components/atoms/_badge.scss
src/components/atoms/_index.scss
src/utils/mixins/_badge.scss
src/utils/mixins/_index.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss
stories/badge.stories.js

Component PR: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/258
https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=4394%3A60463

SYM-4424: Badge

---

src/variables/themes/_dark.scss

EIS-3537 - fix Badge default color

---

src/components/atoms/_avatar.scss

APP-4346 - fix(Avatar): Rename badge class

---

src/components/atoms/_badge.scss
stories/badge.stories.js

- Add size variants to the Badge (size, medium)

feat: badge sizes

---

src/uitoolkit-components/_select.scss
src/variables/colors/_statics.scss

- Added styles to the Dropdown close icon for the keyboard navigation. 
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4343)

APP-4343 Added styles to close-icon

---

src/components/containers/_text-ellipsis.scss
stories/text-ellipsis.stories.js

- Added default 1 line ellipsis per discussion with @symphony-adnane

Updated default for Text Ellipsis

---

src/uitoolkit-components/_select.scss
src/variables/colors/_statics.scss

- Update focus styles using box-shadow

APP-4343 Update focus styles

---

src/uitoolkit-components/_select.scss
src/variables/colors/_statics.scss

Reverts SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles#126
https://user-images.githubusercontent.com/63653674/130448991-0c0222f9-6d94-4e9a-9003-70bc54943c5b.mp4

Revert "APP-4343 Update focus styles"

---

src/components/atoms/_button.scss
src/utils/mixins/_buttons.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss
stories/button.stories.js

- Migration to the button Component
Variants:
Sizes:

APP-4455 SDS Button 

---

src/components/atoms/_button.scss
src/utils/mixins/_buttons.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss
stories/button.stories.js

- Padding on small and large buttons
- Destructive well displayed on Styles
- Tertiary Accent instead of Active
- Color palette on dark mode
- Loading large button padding was too small

APP-4546 Button bug fixes

---

src/utils/mixins/_buttons.scss
src/variables/themes/_dark.scss
src/variables/themes/accessors/colors/_index.scss
stories/button.stories.js

- Added focus style to the Button component
https://user-images.githubusercontent.com/68587873/135471859-df5c685d-f866-4076-bdc7-bb16df58884b.mp4
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4528)

APP-4528 Button - Focus style

---

src/components/atoms/_dialog.scss
src/components/atoms/_drawer.scss
src/components/atoms/_dropdown-menu.scss
src/components/atoms/_select.scss
src/components/molecules/_inputGroup.scss
src/utils/mixins/_list.scss
stories/stories.scss

Decrease output css file size:
- Replacing extend rule 
- Removed duplicated @extend from tk-input 
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4574)

APP-4574 Replace @extend rule

---

publish.sh

Reverts SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles#153

Revert "APP-4625 post a webhook message only if it is an official release"

---

src/components/atoms/_divider.scss
src/components/atoms/_index.scss
src/variables/themes/_dark.scss

the style for the divider was not correctly set.

EIS-3927 - divider style fix

---

src/components/atoms/_dropdown-menu.scss
stories/dropdownMenu.stories.js

- padding left too big
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4695)

APP-4695 Fix padding dropdown menu

---

package.json
yarn.lock

Upgrade StoryBook from 6.3.5 to v6.4.9

Upgrade StoryBook from 6.3.5 to v6.4.9

---

package.json
yarn.lock

Reverts SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles#190

Revert "Upgrade StoryBook from 6.3.5 to v6.4.9"

---

README.md

**Jira ticket**
https://perzoinc.atlassian.net/browse/APP-4758
**Changes**
Add a section to define the Browser support.
(IE11 will be officially retired by Microsoft on June 15, 2022. See article)
**Demo**

APP-4758 Add Browser support section

---

README.md

Update Readme with Visual Testing steps

APP-4535 - Update Readme with Visual Testing steps

---

src/uitoolkit-components/_select.scss

- Fix dropdown padding
- Fix medium size dropdown
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/APP-4797)

APP-4797 Fix dropdown padding

---

src/components/atoms/_input.scss
src/uitoolkit-components/_select.scss

- Updated small input font-size
- Update multi-select sizes
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/APP-4787 )

APP-4787 Updated small input font-size
